twig_event:
    events:
        base:
            blocks:
                hello_world:
                    type: template
                    path: hello_world.html.twig
        hello_world:
            blocks:
                hello_twitter:
                    type: component
                    path: hello_twitter
