name: Split Packages

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
        tags:
            - '*'
    workflow_dispatch: ~

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml
    split_monorepo:
        needs: ci
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - { name: 'TwigHooks' }
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Split of ${{ matrix.package.name }}
                uses: alphpaca/monoplus-split-action@2022.1-beta2
                with:
                    package_path: 'src/${{ matrix.package.name }}'
                    personal_access_token: ${{ secrets.MONOPLUS_PAT }}
                    git_username: 'jakubtobiasz'
                    git_email: 'jakub.tobiasz@icloud.com'
                    repository_owner: "Sylius"
                    repository_name: "${{ matrix.package.name }}"
