name: Split Packages

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
        tags:
            - '*'
    workflow_dispatch: ~

jobs:
    ci:
        name: "Continuous Integration"
        uses: ./.github/workflows/ci.yaml
    split_monorepo:
        name: "Split packages"
        #needs: ci
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - { name: 'AdminUi' }
                    - { name: 'BootstrapAdminUi' }
                    - { name: 'TwigExtra' }
                    - { name: 'TwigHooks' }
                    - { name: 'UiTranslations' }
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Split of ${{ matrix.package.name }}
                uses: alphpaca/monoplus-split-action@2022.1-beta3
                with:
                    package_path: 'src/${{ matrix.package.name }}'
                    personal_access_token: ${{ secrets.MONOPLUS_PAT }}
                    git_username: 'GSadee'
                    git_email: 'sadowskigp@gmail.com'
                    repository_owner: "Sylius"
                    repository_name: "${{ matrix.package.name }}"
